apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: auto-pe-reusable-wf_latest
on:
  workflow_call: {}
  workflow_dispatch:
permissions:
  scm-token-own: read
  scm-token-org: read

jobs:
  build: 
      steps:
        - name: Build something
          uses: docker://alpine:latest
          shell: sh
          run: echo "Building..."
  policy-exit:
    needs: build
    uses: cloudbees-io/policy-utils/evaluate-policy-context/workflow.yml@v2
    with:
      checkpoint-type: workflow
      checkpoint-position: within

  call-nested-reusable:
    uses: .cloudbees/workflows/auto-pe-reusable-wf-2.yaml
